using Dubox.Application.DTOs;
using Dubox.Domain.Abstraction;
using Dubox.Domain.Entities;
using Dubox.Domain.Enums;
using Dubox.Domain.Shared;
using Mapster;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Dubox.Application.Features.Boxes.Commands;

public class ImportBoxesCommandHandler : IRequestHandler<ImportBoxesCommand, Result<List<BoxDto>>>
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IDbContext _dbContext;

    public ImportBoxesCommandHandler(IUnitOfWork unitOfWork, IDbContext dbContext)
    {
        _unitOfWork = unitOfWork;
        _dbContext = dbContext;
    }

    public async Task<Result<List<BoxDto>>> Handle(ImportBoxesCommand request, CancellationToken cancellationToken)
    {
        // Verify project exists
        var project = await _unitOfWork.Repository<Project>()
            .GetByIdAsync(request.ProjectId, cancellationToken);

        if (project == null)
            return Result.Failure<List<BoxDto>>("Project not found");

        // Get all activity masters for auto-copy
        var activityMasters = await _dbContext.ActivityMasters
            .Where(am => am.IsActive)
            .OrderBy(am => am.OverallSequence)
            .ToListAsync(cancellationToken);

        var importedBoxes = new List<Box>();

        foreach (var boxDto in request.Boxes)
        {
            // Check if box already exists
            var existingBox = await _unitOfWork.Repository<Box>()
                .IsExistAsync(b => b.ProjectId == request.ProjectId && b.BoxTag == boxDto.BoxTag, cancellationToken);

            if (existingBox)
                continue; // Skip duplicate boxes

            // Create QR Code String: PROJECT-CODE_BOX-TAG
            var qrCodeString = $"{project.ProjectCode}_{boxDto.BoxTag}";

            var box = new Box
            {
                ProjectId = request.ProjectId,
                BoxTag = boxDto.BoxTag,
                BoxName = boxDto.BoxName,
                BoxType = boxDto.BoxType,
                Floor = boxDto.Floor,
                Building = boxDto.Building,
                Zone = boxDto.Zone,
                QRCodeString = qrCodeString,
                QRCodeImageUrl = null, // Will be generated by QR service later
                ProgressPercentage = 0,
                Status = "Not Started",
                Length = boxDto.Length,
                Width = boxDto.Width,
                Height = boxDto.Height,
                UnitOfMeasure = UnitOfMeasureEnum.m,
                BIMModelReference = boxDto.BIMModelReference,
                RevitElementId = boxDto.RevitElementId,
                IsActive = true,
                CreatedDate = DateTime.UtcNow
            };

            await _unitOfWork.Repository<Box>().AddAsync(box, cancellationToken);
            importedBoxes.Add(box);

            // Auto-copy activities from ActivityMaster
            await CopyActivitiesToBox(box, boxDto.BoxType, activityMasters, cancellationToken);

            // Add assets if provided
            if (boxDto.Assets != null && boxDto.Assets.Any())
            {
                foreach (var assetDto in boxDto.Assets)
                {
                    var asset = new BoxAsset
                    {
                        BoxId = box.BoxId,
                        AssetType = assetDto.AssetType,
                        AssetCode = assetDto.AssetCode,
                        AssetName = assetDto.AssetName,
                        Quantity = assetDto.Quantity,
                        Unit = assetDto.Unit,
                        Specifications = assetDto.Specifications,
                        Notes = assetDto.Notes,
                        CreatedDate = DateTime.UtcNow
                    };

                    await _unitOfWork.Repository<BoxAsset>().AddAsync(asset, cancellationToken);
                }
            }
        }

        await _unitOfWork.CompleteAsync(cancellationToken);

        // Update project total boxes count
        project.TotalBoxes = await _dbContext.Boxes.CountAsync(b => b.ProjectId == request.ProjectId, cancellationToken);
        _unitOfWork.Repository<Project>().Update(project);
        await _unitOfWork.CompleteAsync(cancellationToken);

        return Result.Success(importedBoxes.Adapt<List<BoxDto>>());
    }

    private async Task CopyActivitiesToBox(Box box, string boxType, List<ActivityMaster> activityMasters, CancellationToken cancellationToken)
    {
        foreach (var activityMaster in activityMasters)
        {
            // Check if activity is applicable to this box type
            if (!string.IsNullOrEmpty(activityMaster.ApplicableBoxTypes))
            {
                var applicableTypes = activityMaster.ApplicableBoxTypes.Split(',', StringSplitOptions.RemoveEmptyEntries);
                if (!applicableTypes.Any(t => t.Trim().Equals(boxType, StringComparison.OrdinalIgnoreCase)))
                {
                    continue; // Skip this activity for this box type
                }
            }

            var boxActivity = new BoxActivity
            {
                BoxId = box.BoxId,
                ActivityMasterId = activityMaster.ActivityMasterId,
                Sequence = activityMaster.OverallSequence,
                Status = "Not Started",
                ProgressPercentage = 0,
                PlannedStartDate = box.ActualStartDate?.AddDays(activityMaster.OverallSequence - 1),
                PlannedEndDate = box.ActualStartDate?.AddDays(activityMaster.OverallSequence - 1 + activityMaster.EstimatedDurationDays),
                MaterialsAvailable = true,
                IsActive = true,
                CreatedDate = DateTime.UtcNow
            };

            await _unitOfWork.Repository<BoxActivity>().AddAsync(boxActivity, cancellationToken);
        }
    }
}

