// <auto-generated />
using System;
using Dubox.Infrastructure.ApplicationContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dubox.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251104164257_usersmangement")]
    partial class usersmangement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dubox.Domain.Entities.ActivityDependency", b =>
                {
                    b.Property<int>("DependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DependencyId"));

                    b.Property<int>("BoxActivityId")
                        .HasColumnType("int");

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LagDays")
                        .HasColumnType("int");

                    b.Property<int>("PredecessorActivityId")
                        .HasColumnType("int");

                    b.HasKey("DependencyId");

                    b.HasIndex("BoxActivityId");

                    b.HasIndex("PredecessorActivityId");

                    b.ToTable("ActivityDependencies");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.ActivityMaster", b =>
                {
                    b.Property<int>("ActivityMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityMasterId"));

                    b.Property<string>("ActivityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActivityDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWIRCheckpoint")
                        .HasColumnType("bit");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int>("StandardDuration")
                        .HasColumnType("int");

                    b.Property<string>("Trade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WIRNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ActivityMasterId");

                    b.HasIndex("ActivityCode")
                        .IsUnique();

                    b.ToTable("ActivityMaster");

                    b.HasData(
                        new
                        {
                            ActivityMasterId = 1,
                            ActivityCode = "ACT-001",
                            ActivityDescription = "Manufacture precast walls, slabs, and structural elements",
                            ActivityName = "Fabrication of boxes",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 1,
                            StandardDuration = 5,
                            Trade = "Precast"
                        },
                        new
                        {
                            ActivityMasterId = 2,
                            ActivityCode = "ACT-002",
                            ActivityDescription = "Transport precast elements to assembly area",
                            ActivityName = "Delivery of elements",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 2,
                            StandardDuration = 3,
                            Trade = "Logistics"
                        },
                        new
                        {
                            ActivityMasterId = 3,
                            ActivityCode = "ACT-003",
                            ActivityDescription = "Perform quality checks and store elements for assembly",
                            ActivityName = "Storage and QC",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "QC",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 3,
                            StandardDuration = 1,
                            Trade = "Quality Control"
                        },
                        new
                        {
                            ActivityMasterId = 4,
                            ActivityCode = "ACT-004",
                            ActivityDescription = "Assemble modules and seal structural joints",
                            ActivityName = "Assembly & joints",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 4,
                            StandardDuration = 4,
                            Trade = "Assembly"
                        },
                        new
                        {
                            ActivityMasterId = 5,
                            ActivityCode = "ACT-005",
                            ActivityDescription = "Install preassembled bathroom PODs",
                            ActivityName = "PODS installation",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 5,
                            StandardDuration = 2,
                            Trade = "Assembly"
                        },
                        new
                        {
                            ActivityMasterId = 6,
                            ActivityCode = "ACT-006",
                            ActivityDescription = "Install preassembled MEP cage",
                            ActivityName = "MEP Cage installation",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 6,
                            StandardDuration = 2,
                            Trade = "Assembly"
                        },
                        new
                        {
                            ActivityMasterId = 7,
                            ActivityCode = "ACT-007",
                            ActivityDescription = "Install electrical conduits during assembly",
                            ActivityName = "Electrical Containment (Assembly)",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 7,
                            StandardDuration = 2,
                            Trade = "Electrical"
                        },
                        new
                        {
                            ActivityMasterId = 8,
                            ActivityCode = "ACT-008",
                            ActivityDescription = "Complete box closures and initial QC inspection",
                            ActivityName = "Box Closure",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = true,
                            Sequence = 8,
                            StandardDuration = 1,
                            Trade = "Assembly",
                            WIRNumber = "WIR-1"
                        },
                        new
                        {
                            ActivityMasterId = 9,
                            ActivityCode = "ACT-009",
                            ActivityDescription = "Install AC units",
                            ActivityName = "Fan Coil Units",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 9,
                            StandardDuration = 2,
                            Trade = "Mechanical"
                        },
                        new
                        {
                            ActivityMasterId = 10,
                            ActivityCode = "ACT-010",
                            ActivityDescription = "Install ducts and insulation",
                            ActivityName = "Ducts & Insulation",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 10,
                            StandardDuration = 2,
                            Trade = "Mechanical"
                        },
                        new
                        {
                            ActivityMasterId = 11,
                            ActivityCode = "ACT-011",
                            ActivityDescription = "Complete drainage piping",
                            ActivityName = "Drainage piping",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 11,
                            StandardDuration = 2,
                            Trade = "Mechanical"
                        },
                        new
                        {
                            ActivityMasterId = 12,
                            ActivityCode = "ACT-012",
                            ActivityDescription = "Complete water piping",
                            ActivityName = "Water Piping",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 12,
                            StandardDuration = 2,
                            Trade = "Mechanical"
                        },
                        new
                        {
                            ActivityMasterId = 13,
                            ActivityCode = "ACT-013",
                            ActivityDescription = "Complete firefighting piping",
                            ActivityName = "Fire Fighting Piping",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = true,
                            Sequence = 13,
                            StandardDuration = 2,
                            Trade = "Mechanical",
                            WIRNumber = "WIR-2"
                        },
                        new
                        {
                            ActivityMasterId = 14,
                            ActivityCode = "ACT-014",
                            ActivityDescription = "Install electrical containment",
                            ActivityName = "Electrical Containment",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 14,
                            StandardDuration = 2,
                            Trade = "Electrical"
                        },
                        new
                        {
                            ActivityMasterId = 15,
                            ActivityCode = "ACT-015",
                            ActivityDescription = "Complete electrical wiring",
                            ActivityName = "Electrical Wiring",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 15,
                            StandardDuration = 2,
                            Trade = "Electrical"
                        },
                        new
                        {
                            ActivityMasterId = 16,
                            ActivityCode = "ACT-016",
                            ActivityDescription = "Install distribution board and ONU panel",
                            ActivityName = "DB and ONU Panel",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 16,
                            StandardDuration = 2,
                            Trade = "Electrical"
                        },
                        new
                        {
                            ActivityMasterId = 17,
                            ActivityCode = "ACT-017",
                            ActivityDescription = "Complete drywall framing for partitions",
                            ActivityName = "Dry Wall Framing",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = true,
                            Sequence = 17,
                            StandardDuration = 1,
                            Trade = "Finishing",
                            WIRNumber = "WIR-3"
                        },
                        new
                        {
                            ActivityMasterId = 18,
                            ActivityCode = "ACT-018",
                            ActivityDescription = "Install false ceilings",
                            ActivityName = "False Ceiling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 18,
                            StandardDuration = 1,
                            Trade = "Finishing"
                        },
                        new
                        {
                            ActivityMasterId = 19,
                            ActivityCode = "ACT-019",
                            ActivityDescription = "Install floor and wall tiles",
                            ActivityName = "Tile Fixing",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 19,
                            StandardDuration = 2,
                            Trade = "Finishing"
                        },
                        new
                        {
                            ActivityMasterId = 20,
                            ActivityCode = "ACT-020",
                            ActivityDescription = "Complete painting",
                            ActivityName = "Painting (Internal & External)",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 20,
                            StandardDuration = 2,
                            Trade = "Finishing"
                        },
                        new
                        {
                            ActivityMasterId = 21,
                            ActivityCode = "ACT-021",
                            ActivityDescription = "Fix kitchenettes and counters",
                            ActivityName = "Kitchenette and Counters",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 21,
                            StandardDuration = 2,
                            Trade = "Finishing"
                        },
                        new
                        {
                            ActivityMasterId = 22,
                            ActivityCode = "ACT-022",
                            ActivityDescription = "Install doors",
                            ActivityName = "Doors",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 22,
                            StandardDuration = 1,
                            Trade = "Finishing"
                        },
                        new
                        {
                            ActivityMasterId = 23,
                            ActivityCode = "ACT-023",
                            ActivityDescription = "Install windows",
                            ActivityName = "Windows",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = true,
                            Sequence = 23,
                            StandardDuration = 1,
                            Trade = "Finishing",
                            WIRNumber = "WIR-4"
                        },
                        new
                        {
                            ActivityMasterId = 24,
                            ActivityCode = "ACT-024",
                            ActivityDescription = "Install switches and sockets",
                            ActivityName = "Switches & Sockets",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 24,
                            StandardDuration = 2,
                            Trade = "Electrical"
                        },
                        new
                        {
                            ActivityMasterId = 25,
                            ActivityCode = "ACT-025",
                            ActivityDescription = "Install light fittings",
                            ActivityName = "Light Fittings",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 25,
                            StandardDuration = 2,
                            Trade = "Electrical"
                        },
                        new
                        {
                            ActivityMasterId = 26,
                            ActivityCode = "ACT-026",
                            ActivityDescription = "Install chilled water piping",
                            ActivityName = "Copper Piping",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 26,
                            StandardDuration = 2,
                            Trade = "Mechanical"
                        },
                        new
                        {
                            ActivityMasterId = 27,
                            ActivityCode = "ACT-027",
                            ActivityDescription = "Install sanitary fixtures",
                            ActivityName = "Sanitary Fittings - Kitchen",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 27,
                            StandardDuration = 2,
                            Trade = "Mechanical"
                        },
                        new
                        {
                            ActivityMasterId = 28,
                            ActivityCode = "ACT-028",
                            ActivityDescription = "Install thermostats",
                            ActivityName = "Thermostats",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 28,
                            StandardDuration = 2,
                            Trade = "Mechanical"
                        },
                        new
                        {
                            ActivityMasterId = 29,
                            ActivityCode = "ACT-029",
                            ActivityDescription = "Install air outlets",
                            ActivityName = "Air Outlet",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 29,
                            StandardDuration = 2,
                            Trade = "Mechanical"
                        },
                        new
                        {
                            ActivityMasterId = 30,
                            ActivityCode = "ACT-030",
                            ActivityDescription = "Install sprinkler system",
                            ActivityName = "Sprinkler",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 30,
                            StandardDuration = 2,
                            Trade = "Mechanical"
                        },
                        new
                        {
                            ActivityMasterId = 31,
                            ActivityCode = "ACT-031",
                            ActivityDescription = "Install smoke detectors",
                            ActivityName = "Smoke Detector",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "MEP",
                            IsActive = true,
                            IsWIRCheckpoint = true,
                            Sequence = 31,
                            StandardDuration = 2,
                            Trade = "Mechanical",
                            WIRNumber = "WIR-5"
                        },
                        new
                        {
                            ActivityMasterId = 32,
                            ActivityCode = "ACT-032",
                            ActivityDescription = "Install ironmongery (locks, handles, accessories)",
                            ActivityName = "Iron Mongeries",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Civil",
                            IsActive = true,
                            IsWIRCheckpoint = false,
                            Sequence = 32,
                            StandardDuration = 2,
                            Trade = "Finishing"
                        },
                        new
                        {
                            ActivityMasterId = 33,
                            ActivityCode = "ACT-033",
                            ActivityDescription = "Conduct comprehensive final inspection and wrap modules for delivery",
                            ActivityName = "Inspection & Wrapping",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "QC",
                            IsActive = true,
                            IsWIRCheckpoint = true,
                            Sequence = 33,
                            StandardDuration = 1,
                            Trade = "Quality Control",
                            WIRNumber = "WIR-6"
                        });
                });

            modelBuilder.Entity("Dubox.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditId");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Box", b =>
                {
                    b.Property<Guid>("BoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BoxName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BoxTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BoxType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Building")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Not Started");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProgressPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("QRCodeImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RFIDTag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Zone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BoxId");

                    b.HasIndex("BoxTag")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("QRCode")
                        .IsUnique();

                    b.ToTable("Boxes");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.BoxActivity", b =>
                {
                    b.Property<int>("BoxActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoxActivityId"));

                    b.Property<int>("ActivityMasterId")
                        .HasColumnType("int");

                    b.Property<int>("ActivitySequence")
                        .HasColumnType("int");

                    b.Property<int?>("ActualDuration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedTeamId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlannedDuration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlannedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProgressPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Not Started");

                    b.HasKey("BoxActivityId");

                    b.HasIndex("ActivityMasterId");

                    b.HasIndex("AssignedTeamId");

                    b.HasIndex("BoxId");

                    b.HasIndex("Status");

                    b.HasIndex("BoxId", "Status");

                    b.ToTable("BoxActivities");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.BoxAsset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AssetDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AssetType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AssetId");

                    b.HasIndex("BoxId");

                    b.ToTable("BoxAssets");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.BoxCost", b =>
                {
                    b.Property<int>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostId"));

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BudgetedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CostType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CostId");

                    b.HasIndex("BoxId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BoxCosts");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.BoxLocationHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("MovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("MovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MovedFromLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RFIDReadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("HistoryId");

                    b.HasIndex("BoxId");

                    b.HasIndex("LocationId");

                    b.HasIndex("MovedFromLocationId");

                    b.ToTable("BoxLocationHistory");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.BoxMaterial", b =>
                {
                    b.Property<int>("BoxMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoxMaterialId"));

                    b.Property<DateTime?>("AllocatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("AllocatedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConsumedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ConsumedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RequiredQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BoxMaterialId");

                    b.HasIndex("BoxId");

                    b.HasIndex("MaterialId");

                    b.ToTable("BoxMaterials");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.CostCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("CostCategories");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.DailyProductionLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int?>("ActivityMasterId")
                        .HasColumnType("int");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ManHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ProgressAchieved")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("ActivityMasterId");

                    b.HasIndex("BoxId");

                    b.HasIndex("TeamId");

                    b.HasIndex("LogDate", "TeamId");

                    b.ToTable("DailyProductionLog");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.FactoryLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Bay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LocationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Row")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocationId");

                    b.HasIndex("LocationCode")
                        .IsUnique();

                    b.ToTable("FactoryLocations");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("GroupId");

                    b.HasIndex("GroupName")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.GroupRole", b =>
                {
                    b.Property<Guid>("GroupRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("GroupId", "RoleId")
                        .IsUnique();

                    b.ToTable("GroupRoles");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<decimal?>("CurrentStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("MinimumStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReorderLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaterialId");

                    b.HasIndex("MaterialCode")
                        .IsUnique();

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.MaterialTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<Guid?>("BoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionId");

                    b.HasIndex("BoxId");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialTransactions");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RelatedActivityId")
                        .HasColumnType("int");

                    b.Property<Guid?>("RelatedBoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetUser")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NotificationId");

                    b.HasIndex("RelatedActivityId");

                    b.HasIndex("RelatedBoxId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.ProgressUpdate", b =>
                {
                    b.Property<int>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpdateId"));

                    b.Property<int?>("BoxActivityId")
                        .HasColumnType("int");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IssuesEncountered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WorkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UpdateId");

                    b.HasIndex("BoxActivityId");

                    b.HasIndex("BoxId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UpdateDate");

                    b.HasIndex("BoxId", "UpdateDate");

                    b.ToTable("ProgressUpdates");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectCode")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.QualityIssue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IssueId"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssueDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReportedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolutionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("WIRId")
                        .HasColumnType("int");

                    b.HasKey("IssueId");

                    b.HasIndex("BoxId");

                    b.HasIndex("Status");

                    b.HasIndex("WIRId");

                    b.ToTable("QualityIssues");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Risk", b =>
                {
                    b.Property<int>("RiskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiskId"));

                    b.Property<Guid?>("BoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IdentifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Impact")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MitigationPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Probability")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RiskCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RiskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RiskId");

                    b.HasIndex("BoxId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TeamCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TeamLeaderName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TeamSize")
                        .HasColumnType("int");

                    b.Property<string>("Trade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeamId");

                    b.HasIndex("TeamCode")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("TeamMemberId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.UserGroup", b =>
                {
                    b.Property<Guid>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserGroupId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique();

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.WIRChecklistItem", b =>
                {
                    b.Property<int>("ChecklistItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChecklistItemId"));

                    b.Property<string>("CheckpointDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReferenceDocument")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("WIRId")
                        .HasColumnType("int");

                    b.HasKey("ChecklistItemId");

                    b.HasIndex("WIRId");

                    b.ToTable("WIRChecklistItems");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.WIRCheckpoint", b =>
                {
                    b.Property<int>("WIRId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WIRId"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("BoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InspectorRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WIRDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WIRName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WIRNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("WIRId");

                    b.HasIndex("BoxId");

                    b.ToTable("WIRCheckpoints");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.ActivityDependency", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.BoxActivity", "BoxActivity")
                        .WithMany("Dependencies")
                        .HasForeignKey("BoxActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dubox.Domain.Entities.BoxActivity", "PredecessorActivity")
                        .WithMany("DependentActivities")
                        .HasForeignKey("PredecessorActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoxActivity");

                    b.Navigation("PredecessorActivity");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Box", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Project", "Project")
                        .WithMany("Boxes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.BoxActivity", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.ActivityMaster", "ActivityMaster")
                        .WithMany("BoxActivities")
                        .HasForeignKey("ActivityMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dubox.Domain.Entities.Team", "AssignedTeam")
                        .WithMany("AssignedActivities")
                        .HasForeignKey("AssignedTeamId");

                    b.HasOne("Dubox.Domain.Entities.Box", "Box")
                        .WithMany("Activities")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityMaster");

                    b.Navigation("AssignedTeam");

                    b.Navigation("Box");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.BoxAsset", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Box", "Box")
                        .WithMany("Assets")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.BoxCost", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Box", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dubox.Domain.Entities.CostCategory", "Category")
                        .WithMany("BoxCosts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.BoxLocationHistory", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Box", "Box")
                        .WithMany("LocationHistory")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dubox.Domain.Entities.FactoryLocation", "Location")
                        .WithMany("BoxLocationHistory")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dubox.Domain.Entities.FactoryLocation", "MovedFromLocation")
                        .WithMany()
                        .HasForeignKey("MovedFromLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Box");

                    b.Navigation("Location");

                    b.Navigation("MovedFromLocation");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.BoxMaterial", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Box", "Box")
                        .WithMany("BoxMaterials")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dubox.Domain.Entities.Material", "Material")
                        .WithMany("BoxMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.CostCategory", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.CostCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.DailyProductionLog", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.ActivityMaster", "ActivityMaster")
                        .WithMany()
                        .HasForeignKey("ActivityMasterId");

                    b.HasOne("Dubox.Domain.Entities.Box", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dubox.Domain.Entities.Team", "Team")
                        .WithMany("ProductionLogs")
                        .HasForeignKey("TeamId");

                    b.Navigation("ActivityMaster");

                    b.Navigation("Box");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.GroupRole", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Group", "Group")
                        .WithMany("GroupRoles")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dubox.Domain.Entities.Role", "Role")
                        .WithMany("GroupRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.MaterialTransaction", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Box", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId");

                    b.HasOne("Dubox.Domain.Entities.Material", "Material")
                        .WithMany("Transactions")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.BoxActivity", "RelatedActivity")
                        .WithMany()
                        .HasForeignKey("RelatedActivityId");

                    b.HasOne("Dubox.Domain.Entities.Box", "RelatedBox")
                        .WithMany()
                        .HasForeignKey("RelatedBoxId");

                    b.Navigation("RelatedActivity");

                    b.Navigation("RelatedBox");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.ProgressUpdate", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.BoxActivity", "BoxActivity")
                        .WithMany("ProgressUpdates")
                        .HasForeignKey("BoxActivityId");

                    b.HasOne("Dubox.Domain.Entities.Box", "Box")
                        .WithMany("ProgressUpdates")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dubox.Domain.Entities.Team", "Team")
                        .WithMany("ProgressUpdates")
                        .HasForeignKey("TeamId");

                    b.Navigation("Box");

                    b.Navigation("BoxActivity");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.QualityIssue", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Box", "Box")
                        .WithMany("QualityIssues")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dubox.Domain.Entities.WIRCheckpoint", "WIRCheckpoint")
                        .WithMany("QualityIssues")
                        .HasForeignKey("WIRId");

                    b.Navigation("Box");

                    b.Navigation("WIRCheckpoint");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Risk", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Box", "Box")
                        .WithMany()
                        .HasForeignKey("BoxId");

                    b.HasOne("Dubox.Domain.Entities.Project", "Project")
                        .WithMany("Risks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.UserGroup", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dubox.Domain.Entities.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dubox.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.WIRChecklistItem", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.WIRCheckpoint", "WIRCheckpoint")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("WIRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WIRCheckpoint");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.WIRCheckpoint", b =>
                {
                    b.HasOne("Dubox.Domain.Entities.Box", "Box")
                        .WithMany("WIRCheckpoints")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.ActivityMaster", b =>
                {
                    b.Navigation("BoxActivities");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Box", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Assets");

                    b.Navigation("BoxMaterials");

                    b.Navigation("LocationHistory");

                    b.Navigation("ProgressUpdates");

                    b.Navigation("QualityIssues");

                    b.Navigation("WIRCheckpoints");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.BoxActivity", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("DependentActivities");

                    b.Navigation("ProgressUpdates");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.CostCategory", b =>
                {
                    b.Navigation("BoxCosts");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.FactoryLocation", b =>
                {
                    b.Navigation("BoxLocationHistory");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Group", b =>
                {
                    b.Navigation("GroupRoles");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Material", b =>
                {
                    b.Navigation("BoxMaterials");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Project", b =>
                {
                    b.Navigation("Boxes");

                    b.Navigation("Risks");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Role", b =>
                {
                    b.Navigation("GroupRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.Team", b =>
                {
                    b.Navigation("AssignedActivities");

                    b.Navigation("Members");

                    b.Navigation("ProductionLogs");

                    b.Navigation("ProgressUpdates");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.User", b =>
                {
                    b.Navigation("UserGroups");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Dubox.Domain.Entities.WIRCheckpoint", b =>
                {
                    b.Navigation("ChecklistItems");

                    b.Navigation("QualityIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
